#!/usr/bin/env bash
# Container entrypoint.
#
# The app reads its DB connection from includes/config.php, which is gitignored
# and therefore not present in the image. Generate it from DB_* environment
# variables on first start (unless one was mounted in), then hand off to the
# CMD (Apache).
set -euo pipefail

CONFIG_FILE="/var/www/html/includes/config.php"

if [ ! -f "$CONFIG_FILE" ]; then
    if [ -n "${DB_HOST:-}" ] || [ -n "${DB_NAME:-}" ] || [ -n "${DB_USER:-}" ]; then
        echo "docker-entrypoint: generating includes/config.php from DB_* env vars"
        cat > "$CONFIG_FILE" <<PHP
<?php

// Auto-generated by docker-entrypoint.sh from DB_* environment variables.
return [
    'host'     => getenv('DB_HOST') ?: '127.0.0.1',
    'port'     => (int) (getenv('DB_PORT') ?: 3306),
    'database' => getenv('DB_NAME') ?: '',
    'username' => getenv('DB_USER') ?: '',
    'password' => getenv('DB_PASSWORD') ?: '',
];
PHP
        chown www-data:www-data "$CONFIG_FILE"
    else
        echo "docker-entrypoint: WARNING - includes/config.php is missing and no DB_* env vars were provided." >&2
        echo "docker-entrypoint: set DB_HOST/DB_NAME/DB_USER/DB_PASSWORD or mount includes/config.php." >&2
    fi
fi

exec "$@"
