<?php
// wp-plugin/woo-mgmt-agent/includes/class-wma-settings.php

defined('ABSPATH') || exit;

/**
 * Pairing screen under Settings -> Woo Management Agent: admin pastes the
 * token and base URL generated by woo-managment. Both are plain options
 * (not hashed) because the plugin must present this same token back to
 * woo-managment on every outbound call (presign requests), not just verify
 * inbound ones.
 */
class Wma_Settings
{
    public static function get_token(): string
    {
        return (string) get_option('wma_token', '');
    }

    public static function get_base_url(): string
    {
        return rtrim((string) get_option('wma_base_url', ''), '/');
    }

    public static function get_channel(): string
    {
        return get_option('wma_update_channel', 'stable') === 'beta' ? 'beta' : 'stable';
    }

    public static function register(): void
    {
        add_action('admin_menu', [self::class, 'add_menu']);
        add_action('admin_init', [self::class, 'register_settings']);
    }

    public static function add_menu(): void
    {
        add_options_page(
            'Woo Management Agent',
            'Woo Management Agent',
            'manage_options',
            'wma-settings',
            [self::class, 'render_page']
        );
    }

    public static function register_settings(): void
    {
        register_setting('wma', 'wma_token');
        register_setting('wma', 'wma_base_url');
        register_setting('wma', 'wma_update_channel');
    }

    public static function render_page(): void
    {
        if (!current_user_can('manage_options')) {
            return;
        }
        $wooActive = class_exists('WooCommerce');

        echo '<div class="wrap"><h1>Woo Management Agent</h1>';
        echo '<p>WooCommerce: ' . ($wooActive ? '<strong style="color:green">detected</strong>' : '<strong style="color:red">not detected</strong>') . '</p>';

        echo '<form method="post" action="options.php">';
        settings_fields('wma');
        echo '<table class="form-table">';
        echo '<tr><th><label for="wma_base_url">woo-managment base URL</label></th><td>';
        echo '<input type="url" id="wma_base_url" name="wma_base_url" class="regular-text" value="' . esc_attr(self::get_base_url()) . '" required></td></tr>';
        echo '<tr><th><label for="wma_token">Pairing token</label></th><td>';
        echo '<input type="text" id="wma_token" name="wma_token" class="regular-text" value="' . esc_attr(self::get_token()) . '" required></td></tr>';
        echo '<tr><th><label for="wma_update_channel">Update channel</label></th><td>';
        echo '<select id="wma_update_channel" name="wma_update_channel">';
        foreach (['stable' => 'Stable', 'beta' => 'Beta'] as $value => $label) {
            $selected = self::get_channel() === $value ? ' selected' : '';
            echo '<option value="' . esc_attr($value) . '"' . $selected . '>' . esc_html($label) . '</option>';
        }
        echo '</select></td></tr>';
        echo '</table>';
        submit_button('Save pairing');
        echo '</form></div>';
    }
}
