<?php

require_once __DIR__ . '/../../includes/helpers.php';
install_json_fatal_handler();
require_once __DIR__ . '/../../includes/Settings.php';
require_once __DIR__ . '/../../includes/BackupManager.php';
require_once __DIR__ . '/../../includes/AppJetBackupManager.php';

// No session here — cron jobs don't carry a browser session, so this
// endpoint is authenticated with a long random token instead (generated by
// BackupManager::ensureCronToken(), shown on Admin -> Backups).
$token = (string) ($_GET['token'] ?? '');
$expected = (string) get_setting('backup_cron_token');

if ($expected === '' || !hash_equals($expected, $token)) {
    json_response(['error' => 'Invalid token'], 403);
}

$type = ($_GET['type'] ?? 'database') === 'full' ? 'full' : 'database';
$result = AppJetBackupManager::isConfigured() ? AppJetBackupManager::run() : BackupManager::run($type);

json_response($result, $result['ok'] ? 200 : 502);
